### ISSUE TITLE
Why import prometheus_client and don't use it?)

### ISSUE THREAD

**Issue by alekseyen** [everydaycodings/Text-Summarization-using-NLP#1]
Hey man, it will be really interesting to see metic aggregation for this project

Just find `from prometheus_client import Summary` :)

**Comment by everydaycodings** [comment]
Ya thanks for your concern, I will remove the line [from prometheus_client import Summary](https://github.com/everydaycodings/Text-Summarization-using-NLP/blob/20f3c1bd2a3f91c468950633562fb9d9cab7b738/app.py#L1) I think I wrote it with mistake.

Thanks
